MonDexNames: ; 0x29892
	db "BULBIZARRE@"
	db "HERBIZARRE@"
	db "FLORIZARRE@"
	db "SALAMÈCHE @"
	db "REPTINCEL @"
	db "DRACAUFEU @"
	db "CARAPUCE  @"
	db "CARABAFFE @"
	db "TORTANK   @"
	db "CHENIPAN  @"
	db "CHRYSACIER@"
	db "PAPILUSION@"
	db "ASPICOT   @"
	db "COCONFORT @"
	db "DARDARGNAN@"
	db "ROUCOOL   @"
	db "ROUCOUPS  @"
	db "ROUCARNAGE@"
	db "RATTATA   @"
	db "RATTATAC  @"
	db "PIAFABEC  @"
	db "RAPASDEPIC@"
	db "ABO       @"
	db "ARBOK     @"
	db "PIKACHU   @"
	db "RAICHU    @"
	db "SABELETTE @"
	db "SABLAIREAU@"
	db "NIDORAN♂  @"
	db "NIDORINA  @"
	db "NIDOQUEEN @"
	db "NIDORAN♀  @"
	db "NIDORINO  @"
	db "NIDOKING  @"
	db "MÉLOFÉE   @"
	db "MÉLODELFE @"
	db "GOUPIX    @"
	db "FEUNARD   @"
	db "RONDOUDOU @"
	db "GRODOUDOU @"
	db "NOSFERAPTI@"
	db "NOSFERALTO@"
	db "MYSTHERBE @"
	db "ORTIDE    @"
	db "RAFFLESIA @"
	db "PARAS     @"
	db "PARASECT  @"
	db "MIMITOSS  @"
	db "AÉROMITE  @"
	db "TAUPIQUEUR@"
	db "TRIOPIKEUR@"
	db "MIAOUSS   @"
	db "PERSIAN   @"
	db "PSYKOKWAK @"
	db "AKWAKWAK  @"
	db "FÉROSINGE @"
	db "COLOSSINGE@"
	db "CANINOS   @"
	db "ARCANIN   @"
	db "PTITARD   @"
	db "TÊTARTE   @"
	db "TARTARD   @"
	db "ABRA      @"
	db "KADABRA   @"
	db "ALAKAZAM  @"
	db "MACHOC    @"
	db "MACHOPEUR @"
	db "MACKOGNEUR@"
	db "CHÉTIFLOR @"
	db "BOUSTIFLOR@"
	db "EMPIFLOR  @"
	db "TENTACOOL @"
	db "TENTACRUEL@"
	db "RACAILLOU @"
	db "GRAVALANCH@"
	db "GROLEM    @"
	db "PONYTA    @"
	db "GALOPA    @"
	db "RAMOLOSS  @"
	db "FLAGADOSS @"
	db "MAGNÉTI   @"
	db "MAGNÉTON  @"
	db "CANARTICHO@"
	db "DODUO     @"
	db "DODRIO    @"
	db "OTARIA    @"
	db "LAMANTINE @"
	db "TADMORV   @"
	db "GROTADMORV@"
	db "KOKIYAS   @"
	db "CRUSTABRI @"
	db "FANTOMINUS@"
	db "SPECTRUM  @"
	db "ECTOPLASMA@"
	db "ONIX      @"
	db "SOPORIFIK @"
	db "HYPNOMADE @"
	db "KRABBY    @"
	db "KRABBOSS  @"
	db "VOLTORBE  @"
	db "ÉLECTRODE @"
	db "NOEUNOEUF @"
	db "NOADKOKO  @"
	db "OSSELAIT  @"
	db "OSSATUEUR @"
	db "KICKLEE   @"
	db "TYGNON    @"
	db "EXCELANGUE@"
	db "SMOGO     @"
	db "SMOGOGO   @"
	db "RHINOCORNE@"
	db "RHINOFÉROS@"
	db "LEVEINARD @"
	db "SAQUEDENEU@"
	db "KANGOUREX @"
	db "HYPOTREMPE@"
	db "HYPOCÉAN  @"
	db "POISSIRÈNE@"
	db "POISSOROY @"
	db "STARI     @"
	db "STAROSS   @"
	db "M.MIME    @"
	db "INSÉCATEUR@"
	db "LIPPOUTOU @"
	db "ÉLEKTEK   @"
	db "MAGMAR    @"
	db "SCARABRUTE@"
	db "TAUROS    @"
	db "MAGICARPE @"
	db "LÉVIATOR  @"
	db "LOKHLASS  @"
	db "MÉTAMORPH @"
	db "ÉVOLI     @"
	db "AQUALI    @"
	db "VOLTALI   @"
	db "PYROLI    @"
	db "PORYGON   @"
	db "AMONITA   @"
	db "AMONISTAR @"
	db "KABUTO    @"
	db "KABUTOPS  @"
	db "PTÉRA     @"
	db "RONFLEX   @"
	db "ARTIKODIN @"
	db "ÉLECTHOR  @"
	db "SULFURA   @"
	db "MINIDRACO @"
	db "DRACO     @"
	db "DRACOLOSSE@"
	db "MEWTWO    @"
	db "MEW       @"
	db "GERMIGNON @"
	db "MACRONIUM @"
	db "MÉGANIUM  @"
	db "HÉRICENDRE@"
	db "FEURISSON @"
	db "TYPHLOSION@"
	db "KAIMINUS  @"
	db "CROCRODIL @"
	db "ALIGATUEUR@"
	db "FOUINETTE @"
	db "FOUINAR   @"
	db "HOOTHOOT  @"
	db "NOARFANG  @"
	db "COXY      @"
	db "COXYCLAQUE@"
	db "MIMIGAL   @"
	db "MIGALOS   @"
	db "NOSTENFER @"
	db "LOUPIO    @"
	db "LANTURN   @"
	db "PICHU     @"
	db "MÉLO      @"
	db "TOUDOUDOU @"
	db "TOGEPI    @"
	db "TOGETIC   @"
	db "NATU      @"
	db "XATU      @"
	db "WATTOUAT  @"
	db "LAINERGIE @"
	db "PHARAMP   @"
	db "JOLIFLOR  @"
	db "MARILL    @"
	db "AZUMARILL @"
	db "SIMULARBRE@"
	db "TARPAUD   @"
	db "GRANIVOL  @"
	db "FLORAVOL  @"
	db "COTOVOL   @"
	db "CAPUMAIN  @"
	db "TOURNEGRIN@"
	db "HÉLIATRONC@"
	db "YANMA     @"
	db "AXOLOTO   @"
	db "MARAÏSTE  @"
	db "MENTALI   @"
	db "NOCTALI   @"
	db "CORNÈBRE  @"
	db "ROIGADA   @"
	db "FEUFORÊVE @"
	db "ZARBI     @"
	db "QULBUTOKÉ @"
	db "GIRAFARIG @"
	db "POMDEPIK  @"
	db "FORETRESS @"
	db "INSOLOURDO@"
	db "SCORPLANE @"
	db "STEELIX   @"
	db "SNUBBULL  @"
	db "GRANBULL  @"
	db "QWILFISH  @"
	db "CIZAYOX   @"
	db "CARATROC  @"
	db "SCARHINO  @"
	db "FARFURET  @"
	db "TEDDIURSA @"
	db "URSARING  @"
	db "LIMAGMA   @"
	db "VOLCAROPOD@"
	db "MARCACRIN @"
	db "COCHIGNON @"
	db "CORAYON   @"
	db "REMORAID  @"
	db "OCTILLERY @"
	db "CADOIZO   @"
	db "DÉMANTA   @"
	db "AIRMURE   @"
	db "MALOSSE   @"
	db "DÉMOLOSSE @"
	db "HYPOROI   @"
	db "PHANPY    @"
	db "DONPHAN   @"
	db "PORYGON2  @"
	db "CERFROUSSE@"
	db "QUEULORIOR@"
	db "DÉBUGANT  @"
	db "KAPOÉRA   @"
	db "LIPPOUTI  @"
	db "ÉLEKID    @"
	db "MAGBY     @"
	db "ÉCRÉMEUH  @"
	db "LEUPHORIE @"
	db "RAIKOU    @"
	db "ENTEI     @"
	db "SUICUNE   @"
	db "EMBRYLEX  @"
	db "YMPHECT   @"
	db "TYRANOCIF @"
	db "LUGIA     @"
	db "HO-OH     @"
	db "CÉLÉBI    @"
	db "ARCKO     @"
	db "MASSKO    @"
	db "JUNGKO    @"
	db "POUSSIFEU @"
	db "GALIFEU   @"
	db "BRASÉGALI @"
	db "GOBOU     @"
	db "FLOBIO    @"
	db "LAGGRON   @"
	db "MEDHYÈNA  @"
	db "GRAHYÈNA  @"
	db "ZIGZATON  @"
	db "LINÉON    @"
	db "CHENIPOTTE@"
	db "ARMULYS   @"
	db "CHARMILLON@"
	db "BLINDALYS @"
	db "PAPINOX   @"
	db "NÉNUPIOT  @"
	db "LOMBRE    @"
	db "LUDICOLO  @"
	db "GRAINIPIOT@"
	db "PIFEUIL   @"
	db "TENGALICE @"
	db "NIRONDELLE@"
	db "HÉLÉDELLE @"
	db "GOÉLISE   @"
	db "BÉKIPAN   @"
	db "TARSAL    @"
	db "KIRLIA    @"
	db "GARDEVOIR @"
	db "ARAKDO    @"
	db "MASKADRA  @"
	db "BALIGNON  @"
	db "CHAPIGNON @"
	db "PARÉCOOL  @"
	db "VIGOROTH  @"
	db "MONAFLÉMIT@"
	db "NINGALE   @"
	db "NINJASK   @"
	db "MUNJA     @"
	db "CHUCHMUR  @"
	db "RAMBOUM   @"
	db "BROUHABAM @"
	db "MAKUHITA  @"
	db "HARIYAMA  @"
	db "AZURILL   @"
	db "TARINOR   @"
	db "SKITTY    @"
	db "DELCATTY  @"
	db "TÉNÉFIX   @"
	db "MYSDIBULE @"
	db "GALÉKID   @"
	db "GALEGON   @"
	db "GALEKING  @"
	db "MÉDITIKKA @"
	db "CHARMINA  @"
	db "DYNAVOLT  @"
	db "ÉLECSPRINT@"
	db "POSIPI    @"
	db "NÉGAPI    @"
	db "MUCIOLE   @"
	db "LUMIVOLE  @"
	db "ROSÉLIA   @"
	db "GLOUPTI   @"
	db "AVALTOUT  @"
	db "CARVANHA  @"
	db "SHARPEDO  @"
	db "WAILMER   @"
	db "WAILORD   @"
	db "CHAMALLOT @"
	db "CAMÉRUPT  @"
	db "CHARTOR   @"
	db "SPOINK    @"
	db "GRORET    @"
	db "SPINDA    @"
	db "KRAKNOIX  @"
	db "VIBRANINF @"
	db "LIBÉGON   @"
	db "CACNEA    @"
	db "CACTURNE  @"
	db "TYLTON    @"
	db "ALTARIA   @"
	db "MANGRIFF  @"
	db "SÉVIPER   @"
	db "SÉLÉROC   @"
	db "SOLAROC   @"
	db "BARLOCHE  @"
	db "BARBICHA  @"
	db "ÉCRAPINCE @"
	db "COLHOMARD @"
	db "BALBUTO   @"
	db "KAORINE   @"
	db "LILIA     @"
	db "VACILYS   @"
	db "ANORITH   @"
	db "ARMALDO   @"
	db "BARPAU    @"
	db "MILOBELLUS@"
	db "MORPHÉO   @"
	db "KECLEON   @"
	db "POLICHOMBR@"
	db "BRANETTE  @"
	db "SKELÉNOX  @"
	db "TÉRACLOPE @"
	db "TROPIUS   @"
	db "EOKO      @"
	db "ABSOL     @"
	db "OKÉOKÉ    @"
	db "STALGAMIN @"
	db "ONIGLALI  @"
	db "OBALIE    @"
	db "PHOGLEUR  @"
	db "KAIMORSE  @"
	db "COQUIPERL @"
	db "SERPANG   @"
	db "ROSABYSS  @"
	db "RELICANTH @"
	db "LOVDISC   @"
	db "DRABY     @"
	db "DRACKHAUS @"
	db "DRATTAK   @"
	db "TERHAL    @"
	db "METANG    @"
	db "MÉTALOSSE @"
	db "REGIROCK  @"
	db "RÉGICE    @"
	db "REGISTEEL @"
	db "LATIAS    @"
	db "LATIOS    @"
	db "KYOGRE    @"
	db "GROUDON   @"
	db "RAYQUAZA  @"
	db "JIRACHI   @"
	db "DÉOXYS    @"
